# kitty.conf
#
# Author: Wojciech 'KosciaK' Pietrzok
#
# Reference: https://sw.kovidgoyal.net/kitty/conf/
#
# NOTE: To reload config: Ctrl-Shift-F5
#

# ----------------------------------------------------------------------
# Window layout
# ----------------------------------------------------------------------

remember_window_size        no
initial_window_width        80c
initial_window_height       24c

hide_window_decorations     no

draw_minimal_borders        yes
# NOTE: Not yet available in 0.43
draw_window_borders_for_single_window yes

window_border_width         1px

window_margin_width         0
window_padding_width        2   2

active_border_color         #555753
inactive_border_color       #d3d7cf


# ----------------------------------------------------------------------
# Fonts
# ----------------------------------------------------------------------

font_family                 Adwaita Mono
bold_font                   auto
italic_font                 auto
bold_italic_font            auto

font_size                   11.0
modify_font cell_height     +1px

# NOTE: There ara some slight differences in kitty font rendering
#       Mostly in slight colour differences, not sure why
# text_composition_strategy   platform
# text_composition_strategy   legacy
text_composition_strategy   2.0     0.0


# ----------------------------------------------------------------------
# Colors and theme
# ----------------------------------------------------------------------

include themes/tango_light.conf

# Make selection reverse colors
selection_background        none
selection_foreground        none

# NOTE: must be specified explicitely
url_style                   straight


# ----------------------------------------------------------------------
# Cursor
# ----------------------------------------------------------------------

cursor                      none
cursor_text_color           background

cursor_shape                block
cursor_shape_unfocused      hollow

cursor_beam_thickness       1
cursor_underline_thickness  1.5

# shell integration sets cursor to beam, to avoid it:
shell_integration   no-cursor

# Use system default for blinking
cursor_blink_interval       -1
cursor_stop_blinking_after  10.0

cursor_trail    0


# ----------------------------------------------------------------------
# Scrolling
# ----------------------------------------------------------------------

scrollback                  20000

scrollbar                   always

scrollbar_interactive       yes
scrollbar_jump_on_click     yes

scrollbar_width             0.5
scrollbar_hover_width       1.25
scrollbar_radius            0.75
scrollbar_gap               0.25

scrollbar_handle_opacity        0.5
scrollbar_track_opacity         0.1
scrollbar_track_hover_opacity   0.15

scrollbar_hitbox_expansion      2.0

scrollback_fill_enlarged_window yes


# ----------------------------------------------------------------------
# Mouse
# ----------------------------------------------------------------------

# Hide mouse on typing
mouse_hide_wait             -1


# ----------------------------------------------------------------------
# Bell
# ----------------------------------------------------------------------

enable_audio_bell           yes
visual_bell_duration        0.0


# ----------------------------------------------------------------------
# Tab bar
# ----------------------------------------------------------------------

tab_bar_edge                top
tab_bar_align               left
tab_bar_style               powerline
tab_bar_min_tabs            2

tab_bar_margin_width        0.0
tab_bar_margin_height       0.0     0.0

tab_title_max_length        0

# tab_activity_symbol         none


# ----------------------------------------------------------------------
# Mappings
# ----------------------------------------------------------------------

include mappings.conf

