# kitty.conf
# mappings.conf
#
# Author: Wojciech 'KosciaK' Pietrzok
#
# Reference: https://sw.kovidgoyal.net/kitty/actions/
#


# Default, but let's keep it here for clarity
kitty_mod                   ctrl+shift

# ----------------------------------------------------------------------
# Keyboard
# ----------------------------------------------------------------------

# Ctrl+Insert, Shift+Insert for Copy/Paste
map     ctrl+insert         copy_to_clipboard
map     shift+insert        paste_from_clipboard
map     ctrl+shift+insert   paste_from_clipboard

# Scroll with Shift instead of Ctrl+Shift
map     shift+page_up       scroll_page_up
map     shift+page_down     scroll_page_down
# NOTE: Not sure if it won't break anything
map     shift+up            scroll_line_up
map     shift+down          scroll_line_down

# New windows / tabs always with current working dir
map     kitty_mod+enter     new_window_with_cwd
map     kitty_mod+n         new_os_window_with_cwd
map     kitty_mod+t         new_tab_with_cwd

# Ctrl+Page<Up/Down> to change tabs
map     ctrl+page_up        previous_tab
map     ctrl+page_down      next_tab
# TODO: Consider unmapping Ctrl+Shift+Left/Right

# Ctrl+Shift+Page<Up/Down> to move tabs
map     kitty_mod+.
map     kitty_mod+,
map     kitty_mod+page_down move_tab_forward
map     kitty_mod+page_up   move_tab_backward

# Switch windows
map     kitty_mod+j         next_window
map     kitty_mod+k         previous_window

# Move windows
map     kitty_mod+f
map     kitty_mod+b
map     kitty_mod+alt+j     move_window_forward
map     kitty_mod+alt+k     move_window_backward

# Move current window to top (as first)
map     kitty_mod+`
map     kitty_mod+i     move_window_to_top

# Toogle Stack layout (full window)
map     kitty_mod+o         toggle_layout stack

# Detach window or tab
map     kitty_mod+d         detach_window ask
map     kitty_mod+alt+d     detach_tab ask

# Always ask for confirmation before closing!
map     kitty_mod+w         close_window_with_confirmation
# NOTE: kitty_mod+1 close_tab


# ----------------------------------------------------------------------
# Mouse
# ----------------------------------------------------------------------

# mouse_map ctrl+shift+left release ungrabbed
# mouse_map ctrl+shift+left press ungrabbed

# Rectangular selection with Ctrl[+Shift][+Alt]-LeftClick
mouse_map ctrl+left press ungrabbed mouse_selection rectangle
mouse_map kitty_mod+left press ungrabbed mouse_selection rectangle
mouse_map ctrl+shift+left press ungrabbed mouse_selection rectangle
# NOTE: For some unknown reason Ctrl-Shift alone still don't work in VIM
#       You have to use Ctrl-Shift-Alt

