# ssh.conf
#
# Config for: kitten ssh
#
# See: https://sw.kovidgoyal.net/kitty/kittens/ssh/
#

# ----------------------------------------------------------------------
# Global settings
# ----------------------------------------------------------------------

shell_integration inherited


# ----------------------------------------------------------------------
# *.ant.vpn
# ----------------------------------------------------------------------
hostname *.ant.vpn

# Change TERM to xterm-256color as xterm-kitty might not be available
# NOTE: It can be configured in ~/.ssh/config with SetEnv
env TERM=xterm-256color

