# Adwaita Mono

font_family                 Adwaita Mono
bold_font                   auto
italic_font                 auto
bold_italic_font            auto

# NOTE: Font seems to be 1px higher than DejaVu Sans Mono
modify_font cell_height     -1px

