# direnv.toml
#
# See: https://direnv.net/man/direnv.toml.1.html
#

disable_stdin = true
load_dotenv = true
hide_env_diff = false
log_format = "-"

[general]
disable_stdin = true
load_dotenv = true
hide_env_diff = false
log_format = "-"

[whitelist]
prefix = [
'~/projekty',
'~/work',
'~/src',
]

