" Generated by vim-plug
" pon, 9 sty 2023, 09:51:09
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['ctrlp.vim'].commit = '8b4a9523632049b3b373de1233bef346073b8982'
silent! let g:plugs['nerdtree'].commit = 'fc85a6f07c2cd694be93496ffad75be126240068'
silent! let g:plugs['simpylfold'].commit = 'ff4c85197c5555715093c08a8d4f9d493c4d80cd'
silent! let g:plugs['supertab'].commit = 'f0093ae12a9115498f887199809a6114659fc858'
silent! let g:plugs['tagbar'].commit = 'af3ce7c3cec81f2852bdb0a0651d2485fcd01214'
silent! let g:plugs['vim-commentary'].commit = 'e87cd90dc09c2a203e13af9704bd0ef79303d755'
silent! let g:plugs['vim-css-color'].commit = '1c4b78f5512980227ca747e76f1f6c904f2eb3dc'
silent! let g:plugs['vim-devicons'].commit = '71f239af28b7214eebb60d4ea5bd040291fb7e33'
silent! let g:plugs['vim-nerdtree-syntax-highlight'].commit = '5178ee4d7f4e7761187df30bb709f703d91df18a'
silent! let g:plugs['vim-plug'].commit = 'ddce935b16fbaaf02ac96f9f238deb04d4d33a31'
silent! let g:plugs['vim-polyglot'].commit = 'bc8a81d3592dab86334f27d1d43c080ebf680d42'
silent! let g:plugs['vim-pythonsense'].commit = '9200a57629c904ed2ab8c9b2e8c5649d311794ba'
silent! let g:plugs['vim-repeat'].commit = '24afe922e6a05891756ecf331f39a1f6743d3d5a'
silent! let g:plugs['vim-surround'].commit = '3d188ed2113431cf8dac77be61b842acb64433d9'

PlugUpdate!

