# Alacritty configuration
# 
# Reference:
# - https://alacritty.org/config-alacritty.html
# - https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd

# NOTE: config migrated from previous alacritty.yml
# TODO: Review, update and comment if needed

[general]
live_config_reload = true
import = [
'themes/tango_light.toml',
'fonts/dejavu_sans_mono.toml',
]


[env]
# key-value pairs to be added as enviromental variables


[window]
dimensions = { columns=80, lines=24 }
position = "None"
padding = { x=4, y=1 }
dynamic_padding = true
decorations = "Full"
decorations_theme_variant = "None"
opacity = 1.0
# blur = false
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true
resize_increments = false


[scrolling]
history = 10000
multiplier = 3


[font]
size = 11.0
builtin_box_drawing = true


[colors]
draw_bold_text_with_bright_colors = false


[bell]
animation = "EaseOut"
color = "#c4a000"
duration = 0

[bell.command]
args = ["/usr/share/sounds/freedesktop/stereo/bell.oga", "vol", "0.75"]
program = "play"


[cursor]
blink_interval = 700
blink_timeout = 13
thickness = 0.1
unfocused_hollow = true

[cursor.style]
# NOTE: blinking = "On" messes up cursor blinking in Vim
blinking = "Always"
shape = "Block"


[mouse]
hide_when_typing = true

